### ISSUE TITLE
No Complete command list

### ISSUE THREAD

**Issue by justarandomgeek** [sparkfun/OpenLCD#14]
I can't seem to find a complete command list anywhere - the readme says nothing about commands, and the examples only include the "cheat sheet" list, even the ones that use commands that aren't on it (like custom characters).

**Comment by lewispg228** [comment]
Hey @justarandomgeek ,
Sorry we don't currently have a 100% complete command set. Hopefully this [firmware overview](https://learn.sparkfun.com/tutorials/avr-based-serial-enabled-lcds-hookup-guide/firmware-overview) will be useful to you. The table at the top of this hookup guide section contains all of the most useful commands (and includes a few more than the cheat-sheets in the example code).

However, I just noticed that it omits some of the lower decimal values for setting width and line values. These early commands are actually not as useful anymore, because the new LCD screens check a hardware IO pin (pulled HIGH/LOW with hardware) to see what screen it is and sets the width and line values automatically. This is how we maintain the same firmware across all hardware.

Hope this helps!
-Pete

**Comment by justarandomgeek** [comment]
It's also still missing all the custom-character commands (the example seems to suggest they ought to start at 0x1B? surely the docs should talk about that...), which indicates to me that it's still incomplete - and really, those are far more interesting than the screen-size ones!

To be clear: I'm wanting to use these screens with my own non-arduino boards, and to do that, I'm gonna have to write my own drivers. To do *that*, I need a complete command list, which I can't seem to find *anywhere*.

**Comment by lewispg228** [comment]
Sorry about this. I haven't played around with the [custom char example yet](https://github.com/sparkfun/OpenLCD/blob/master/firmware/Examples/Serial/Example9_Serial_CustomChar/Example9_Serial_CustomChar.ino).  It is one of the more advanced features of these screens, and so we haven't provided as robust documentation for that yet. You are right, it would definitely be nice to get more info about custom char (possibly write up a few more examples) and provide a complete command list.

I will reach out to Nate (who wrote most of this new code for the LCDs). We should be able to pull together a complete command list and have that posted soon.

**Comment by justarandomgeek** [comment]
Looking forward to that! Frankly, this is the first time (in 10+ years) that I've bought a SparkFun product and not loved it - and so far I'm *really* disappointed, you guys are slipping. You used to have perfect docs on every product!

**Comment by nseidle** [comment]
I've added to the [command table](https://learn.sparkfun.com/tutorials/avr-based-serial-enabled-lcds-hookup-guide/firmware-overview). Should be complete now.

For the pertinent code (and my own notes):

* [Record custom char](https://github.com/sparkfun/OpenLCD/blob/master/firmware/OpenLCD/OpenLCD.ino#L379)
* [Display custom char](https://github.com/sparkfun/OpenLCD/blob/master/firmware/OpenLCD/OpenLCD.ino#L215)
* [Write RGB](https://github.com/sparkfun/OpenLCD/blob/master/firmware/OpenLCD/OpenLCD.ino#L220)
* [Display firmware version](https://github.com/sparkfun/OpenLCD/blob/master/firmware/OpenLCD/OpenLCD.ino#L225)

@justarandomgeek - Have a look and let me know if anything doesn't make sense and I'll add to it.
